[project]
name = "attp_core"
classifiers = ["Programming Language :: Python"]
version = "0.2.2"
readme = "README.md"
license = "LICENSE"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "attp_core.rs_api"